// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfboikpyxtuihsvqphrr.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmYm9pa3B5eHR1aWhzdnFwaHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3OTA2NDIsImV4cCI6MjA5MzM2NjY0Mn0.FkPHHjJtwXF4r1aPI0xa3SOxquV_5x8XUWCwAhog9Rk";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});